# https://github.com/marketplace/actions/gitee-pages-action
name: Sync

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # æ³¨æ„åœ¨ Settings->Secrets é…ç½® GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ GitHub æºä»“åº“åœ°å€.
          source-repo: git@github.com:stellae216/Myblog.git
          # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ Gitee ç›®æ ‡ä»“åº“åœ°å€.
          destination-repo: git@gitee.com:stellae/Myblog.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ Gitee ç”¨æˆ·å
          gitee-username: stellae
          # æ³¨æ„åœ¨ Settings->Secrets é…ç½® GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ Gitee ä»“åº“ï¼Œä»“åº“åä¸¥æ ¼åŒºåˆ†å¤§å°å†™ï¼Œè¯·å‡†ç¡®å¡«å†™ï¼Œå¦åˆ™ä¼šå‡ºé”™.
          gitee-repo: stellae/Myblog
          # è¦éƒ¨ç½²çš„åˆ†æ”¯ï¼Œé»˜è®¤æ˜¯ masterï¼Œè‹¥æ˜¯å…¶ä»–åˆ†æ”¯ï¼Œåˆ™éœ€è¦æŒ‡å®šï¼ˆæŒ‡å®šçš„åˆ†æ”¯å¿…é¡»å­˜åœ¨ï¼‰
          branch: main
      - name: ServerChan Â· Serveré…±é€šçŸ¥
        uses: easychen/github-action-server-chan@v1.0.0
        with:
          sendkey: ${{ secrets.ServerJiang_SendKey }}
          title: "ä¸ªäººåšå®¢éƒ¨ç½²æˆåŠŸï¼ğŸ˜"

